<?php
/**
 * Created by PhpStorm.
 * User: wakasann
 * Date: 2020/10/31
 * Time: 22:43
 */

namespace app\api\controller;


class AuthBase extends ApiBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        return json_response(config('status.error'),'error');
    }
}